# Отчет о работе модуля linearalgebra.py

## Аннотация

Разработан модуль linearalgebra.py, находящийся в одной директории с данным отчетом.

Реализованные функции в linearalgebra:
- сложение
- вычитание
- умножение
- деление
- транспонирование
- нахождение определителя матрицы
- нахождение минора матрицы
- нахождение обратной матрицы
- проверка на вырожденность
- проверка на квадратность



Все функции в модуле реализованы с помощью стандартной библиотеки Python.

## План отчета

Интерактивный план отчета.

[Подключение модуля linearalgebra](#linalg)

[Подключение библиотеки numpy](#numpy)

[Переменные](#vars)

[Общий метод вывода результатов работы реализованных функций](#method)

[01. Сложение](#add)

[02. Вычитание](#subtract)

[03. Умножение](#multiply)

[04. Деление, обратная матрица](#divide)

[05. Транспонирование](#transpose)

[06. Определитель](#determinant)

[Общий вывод](#recap)


## Подключение модуля linearalgebra
<a id='linalg'></a>

In [1]:
import linearalgebra as LA

In [2]:
help(LA)

Help on module linearalgebra:

NAME
    linearalgebra

DESCRIPTION
    # Для использования модуля linearalgebra примем 
    # следующее соглашение о записи векторов и матриц.
    #
    # Вектор-строка записывается во вложенный список вида:
    # vector_row = [[x_11, x_12, ..., x_1N]]
    # где x - элемент вектора, 
    # первый индекс - индекс элемента по номеру строки, 
    #     равен 1, так как вектор содержит одну строку;
    # второй индекс - индекс элемента по номеру столбца, 
    #     последний элемент с индексом N, соответсвует числу столбцов(элементов вектора-строки).
    #
    # Вектор-столбец записывается во вложенный список вида:
    # vector_col = [[x_11],
    #               [x_21],
    #               ...,
    #               [x_M1]]
    # где x - элемент вектора-столбца, 
    # первый индекс - индекс элемента по номеру строки, 
    #     последний элемент с индексом M, соответсвует числу строк(элементов вектора-столбца);
    # второй индекс - индекс элемента по номеру 

## Подключение библотеки numpy
<a id='numpy'></a>

Для сравнения результатов работы функций из linearalgebra подключим библиотеку numpy, и будем использовать аналогичные функции.

In [3]:
import numpy as np

## Переменные
<a id='vars'></a>

Создадим переменные, которые будем использовать в ходе проверки функций: 
- A, B, C - квадратные матрицы размером 3x3 (C - вырожденная матрица, для примера)
- X_1, X_2 - вектор-строка
- Y_1, Y_2 - вектор-столбец
- Z - квадратная матрица 2x2

In [4]:
# матрицы (многомерные фложенные списки)
A = [[1, 4, 6],
     [2, 5, 7],
     [3, 9, 8]]

B = [[2, 1, 3],
     [9, 5, 4],
     [7, 8, 6]]

C = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

# векторы-строки
X_1 = [[1, 2, 3]]
X_2 = [[4, 7, 8]]

# веторы-столбцы
Y_1 = [[3],
       [2],
       [4]]
Y_2 = [[4],
       [7], 
       [9]]

# квадратная матрица 2x2
Z = [[1, 2],
     [3, 5]]

Продублируем, наши переменные в объекты numpy, для сравнения.

In [5]:
A_np = np.array(A)
B_np = np.array(B)
C_np = np.array(C)
X_1_np = np.array(X_1)
X_2_np = np.array(X_2)
Y_1_np = np.array(Y_1)
Y_2_np = np.array(Y_2)
Z_np = np.array(Z)

Также создадим списки с нашими объектами, для удобства

In [6]:
list_py_arrays = [A, B, 
                  X_1, X_2, 
                  Y_1, Y_2]
list_np_arrays = [A_np, B_np, 
                  X_1_np, X_2_np, 
                  Y_1_np, Y_2_np]

In [7]:
names = ["Матрицы", None, "Вектор-строка", None, "Вектор-столбец", None]

## Общий метод вывода результатов работы реализованных функций
<a id='method'></a>

Создадим функцию для упрощения анализа результатов работы реализованных функций в сравнении с библиотекой numpy

In [8]:
def get_result_print(name, 
                     py_obj_1, 
                     np_obj_1, 
                     py_obj_2=None, 
                     np_obj_2=None, 
                     function=None, 
                     function_np=None, 
                     scaler=False):
    
    if scaler:
        py_obj_2 = scaler
        np_obj_2 = scaler
    
    print(f"{name}", end="\n\n")
    print("Исходные объекты:", np_obj_1, np_obj_2,
          sep="\n", end="\n\n")
    print("-"*40)
    print("Результат работы функции", 
          function.__doc__.split('.')[0][8:-7],
          end="\n\n")
    print("linearalgebra:")
    print(*function(py_obj_1, py_obj_2),
          sep="\n", end="\n\n")
    print("numpy:")
    print(function_np(np_obj_1, np_obj_2))
    print("="*40, end="\n\n")

## 01. Сложение
<a id='add'></a>

Проверим функцию сложения для матриц, а также векторов - addition.

Сравним результат вычисления с аналогичной функцией из numpy - add.

Сложение производится поэлементно, матрицы должны быть одинаковой размерности.

In [9]:
for i in range(0, len(list_py_arrays), 2):
    get_result_print(names[i], 
                     list_py_arrays[i],
                     list_np_arrays[i],
                     py_obj_2=list_py_arrays[i+1],
                     np_obj_2=list_np_arrays[i+1],
                     function=LA.addition,
                     function_np=np.add)

Матрицы

Исходные объекты:
[[1 4 6]
 [2 5 7]
 [3 9 8]]
[[2 1 3]
 [9 5 4]
 [7 8 6]]

----------------------------------------
Результат работы функции сложения

linearalgebra:
[3, 5, 9]
[11, 10, 11]
[10, 17, 14]

numpy:
[[ 3  5  9]
 [11 10 11]
 [10 17 14]]

Вектор-строка

Исходные объекты:
[[1 2 3]]
[[4 7 8]]

----------------------------------------
Результат работы функции сложения

linearalgebra:
[5, 9, 11]

numpy:
[[ 5  9 11]]

Вектор-столбец

Исходные объекты:
[[3]
 [2]
 [4]]
[[4]
 [7]
 [9]]

----------------------------------------
Результат работы функции сложения

linearalgebra:
[7]
[9]
[13]

numpy:
[[ 7]
 [ 9]
 [13]]



Сложение матриц и векторов с числом, для примера 2 (аргумент scaler)

In [10]:
for i in range(0, len(list_py_arrays), 2):
    get_result_print(names[i], 
                     list_py_arrays[i],
                     list_np_arrays[i],
                     function=LA.addition,
                     function_np=np.add,
                     scaler=2)

Матрицы

Исходные объекты:
[[1 4 6]
 [2 5 7]
 [3 9 8]]
2

----------------------------------------
Результат работы функции сложения

linearalgebra:
[3, 6, 8]
[4, 7, 9]
[5, 11, 10]

numpy:
[[ 3  6  8]
 [ 4  7  9]
 [ 5 11 10]]

Вектор-строка

Исходные объекты:
[[1 2 3]]
2

----------------------------------------
Результат работы функции сложения

linearalgebra:
[3, 4, 5]

numpy:
[[3 4 5]]

Вектор-столбец

Исходные объекты:
[[3]
 [2]
 [4]]
2

----------------------------------------
Результат работы функции сложения

linearalgebra:
[5]
[4]
[6]

numpy:
[[5]
 [4]
 [6]]



Проверим с матрицами разного размера

In [11]:
LA.addition(A, Z)

Невозможно сложить объекты. Разная размерность.


Вывод: функция сложения работает корректно.

## 02. Вычитание
<a id='subtract'></a>

Вычитание матриц и векторов, функция - subtraction.

Сравним результат вычисления с аналогичной функцией из numpy - subtract.

Вычитание производится поэлементно, матрицы должны быть одинаковой размерности.

In [12]:
for i in range(0, len(list_py_arrays), 2):
    get_result_print(names[i], 
                     list_py_arrays[i],
                     list_np_arrays[i],
                     py_obj_2=list_py_arrays[i+1],
                     np_obj_2=list_np_arrays[i+1],
                     function=LA.subtraction,
                     function_np=np.subtract)

Матрицы

Исходные объекты:
[[1 4 6]
 [2 5 7]
 [3 9 8]]
[[2 1 3]
 [9 5 4]
 [7 8 6]]

----------------------------------------
Результат работы функции вычитания

linearalgebra:
[-1, 3, 3]
[-7, 0, 3]
[-4, 1, 2]

numpy:
[[-1  3  3]
 [-7  0  3]
 [-4  1  2]]

Вектор-строка

Исходные объекты:
[[1 2 3]]
[[4 7 8]]

----------------------------------------
Результат работы функции вычитания

linearalgebra:
[-3, -5, -5]

numpy:
[[-3 -5 -5]]

Вектор-столбец

Исходные объекты:
[[3]
 [2]
 [4]]
[[4]
 [7]
 [9]]

----------------------------------------
Результат работы функции вычитания

linearalgebra:
[-1]
[-5]
[-5]

numpy:
[[-1]
 [-5]
 [-5]]



Вычитание числа из матрицы, например 3

In [13]:
for i in range(0, len(list_py_arrays), 2):
    get_result_print(names[i], 
                     list_py_arrays[i],
                     list_np_arrays[i],
                     function=LA.subtraction,
                     function_np=np.subtract,
                     scaler=3)

Матрицы

Исходные объекты:
[[1 4 6]
 [2 5 7]
 [3 9 8]]
3

----------------------------------------
Результат работы функции вычитания

linearalgebra:
[-2, 1, 3]
[-1, 2, 4]
[0, 6, 5]

numpy:
[[-2  1  3]
 [-1  2  4]
 [ 0  6  5]]

Вектор-строка

Исходные объекты:
[[1 2 3]]
3

----------------------------------------
Результат работы функции вычитания

linearalgebra:
[-2, -1, 0]

numpy:
[[-2 -1  0]]

Вектор-столбец

Исходные объекты:
[[3]
 [2]
 [4]]
3

----------------------------------------
Результат работы функции вычитания

linearalgebra:
[0]
[-1]
[1]

numpy:
[[ 0]
 [-1]
 [ 1]]



Используем матрицы разного размера:

In [14]:
LA.subtraction(A, Z)

Невозможно вычесть объекты. Разная размерность.


Вывод: функция вычитания, работает корректно.

## 03. Умножение
<a id='multiply'></a>

Умножение матриц, функция - multiply.

Сравним результат вычисления с аналогичной функцией из numpy - dot.

In [15]:
get_result_print(names[0], 
                 A, 
                 A_np, 
                 py_obj_2=B,
                 np_obj_2=B_np,
                 function=LA.multiply,
                 function_np=np.dot)

Матрицы

Исходные объекты:
[[1 4 6]
 [2 5 7]
 [3 9 8]]
[[2 1 3]
 [9 5 4]
 [7 8 6]]

----------------------------------------
Результат работы функции умножения

linearalgebra:
[80, 69, 55]
[98, 83, 68]
[143, 112, 93]

numpy:
[[ 80  69  55]
 [ 98  83  68]
 [143 112  93]]



Для матриц разной размерности

In [16]:
LA.multiply(A, Z)

Невозможно перемножить объекты. Разная размерность.


Для вектора-строки и вектора столбца

In [17]:
get_result_print("Вектор-строка умноженный на вектор-столбец", 
                 X_1,  
                 X_1_np,
                 py_obj_2=Y_1,
                 np_obj_2=Y_1_np,
                 function=LA.multiply,
                 function_np=np.dot,
                 scaler=False)

Вектор-строка умноженный на вектор-столбец

Исходные объекты:
[[1 2 3]]
[[3]
 [2]
 [4]]

----------------------------------------
Результат работы функции умножения

linearalgebra:
[19]

numpy:
[[19]]



Для матрицы и вектора-столбца

In [18]:
get_result_print("Матрица умноженная на вектор-столбец",
                 A,
                 A_np, 
                 py_obj_2=Y_1,
                 np_obj_2=Y_1_np,
                 function=LA.multiply,
                 function_np=np.dot)

Матрица умноженная на вектор-столбец

Исходные объекты:
[[1 4 6]
 [2 5 7]
 [3 9 8]]
[[3]
 [2]
 [4]]

----------------------------------------
Результат работы функции умножения

linearalgebra:
[35]
[44]
[59]

numpy:
[[35]
 [44]
 [59]]



Для вектора-строки и матрицы

In [19]:
get_result_print("Вектор-строка умноженная на матрицу",
                 X_1, 
                 X_1_np, 
                 py_obj_2=A,
                 np_obj_2=A_np,
                 function=LA.multiply,
                 function_np=np.dot)

Вектор-строка умноженная на матрицу

Исходные объекты:
[[1 2 3]]
[[1 4 6]
 [2 5 7]
 [3 9 8]]

----------------------------------------
Результат работы функции умножения

linearalgebra:
[14, 41, 44]

numpy:
[[14 41 44]]



Умножение матриц и векторов на число, например 10

In [20]:
for i in range(0, len(list_py_arrays), 2):
    get_result_print(names[i], 
                     list_py_arrays[i], 
                     list_np_arrays[i],
                     function=LA.multiply,
                     function_np=np.dot,
                     scaler=10)

Матрицы

Исходные объекты:
[[1 4 6]
 [2 5 7]
 [3 9 8]]
10

----------------------------------------
Результат работы функции умножения

linearalgebra:
[10, 40, 60]
[20, 50, 70]
[30, 90, 80]

numpy:
[[10 40 60]
 [20 50 70]
 [30 90 80]]

Вектор-строка

Исходные объекты:
[[1 2 3]]
10

----------------------------------------
Результат работы функции умножения

linearalgebra:
[10, 20, 30]

numpy:
[[10 20 30]]

Вектор-столбец

Исходные объекты:
[[3]
 [2]
 [4]]
10

----------------------------------------
Результат работы функции умножения

linearalgebra:
[30]
[20]
[40]

numpy:
[[30]
 [20]
 [40]]



Для прямоугольных матриц большей размерности.

In [21]:
A_4x5 = [[1, 2, 3, 4, 5],
         [3, 5, 7, 9, 1],
         [4, 6, 6, 7, 4],
         [7, 5, 5, 8, 9]]

B_5x4 = [[1, 3, 3, 2],
         [3, 5, 7, 9],
         [2, 4, 5, 7],
         [9, 1, 7, 3],
         [8, 7, 4, 2]]

A_4x5_np = np.array(A_4x5)
B_5x4_np = np.array(B_5x4)

In [22]:
get_result_print("Матрица размером 4x5 и матрица 5x4", 
                 A_4x5, 
                 A_4x5_np, 
                 py_obj_2=B_5x4,
                 np_obj_2=B_5x4_np,
                 function=LA.multiply,
                 function_np=np.dot)

Матрица размером 4x5 и матрица 5x4

Исходные объекты:
[[1 2 3 4 5]
 [3 5 7 9 1]
 [4 6 6 7 4]
 [7 5 5 8 9]]
[[1 3 3 2]
 [3 5 7 9]
 [2 4 5 7]
 [9 1 7 3]
 [8 7 4 2]]

----------------------------------------
Результат работы функции умножения

linearalgebra:
[89, 64, 80, 63]
[121, 78, 146, 129]
[129, 101, 149, 133]
[176, 137, 173, 136]

numpy:
[[ 89  64  80  63]
 [121  78 146 129]
 [129 101 149 133]
 [176 137 173 136]]



Вывод: функция умножения работает корректно

## 04. Деление, обратная матрица
<a id='divide'></a>

Деление матриц, функция - divide.

В модуле linearalgebra реализован метод деления матриц по правилам линейной алгебры вида $A\cdot B^{-1}$.

Для деления двух матриц необходимо первую матрицу $A$ умножить на матрицу, обратную второй $B^{-1}$.

В numpy функция divide реализована как поэлементное деление элементов двух матриц, расположенных на соответсвующих позициях.

В linearalgebra функционал поэлементного деления можно включить задав в функции divide аргументу elements значение True.

Функция inverse реализована по следующему алгоритму нахождения обратной матрицы:
1. Определяют, квадратная ли матрица. Если нет, то обратной матрицы для нее не существует.
2. Вычисление определителя матрицы A. Если он не равен нулю, продолжаем решение, иначе - обратной матрицы не существует.
3. Определение алгебраических дополнений.
4. Заполнение союзной (взаимной, присоединённой) матрицы C.
5. Составление обратной матрицы из алгебраических дополнений: каждый элемент присоединённой матрицы C делят на определитель исходной матрицы. 

Результирующая матрица является обратной для исходной матрицы.

Также необходимо провести проверку $A\cdot A^{-1}$, данное произведение при правильных расчетах должно равнятся единичной матрице.

Сравним результат вычисления с аналогичной функцией из numpy - linalg.inv

In [23]:
LA.inverse(A)

[[-1.5333333333333334, 1.4666666666666666, -0.13333333333333333],
 [0.3333333333333333, -0.6666666666666666, 0.3333333333333333],
 [0.2, 0.2, -0.2]]

In [24]:
np.linalg.inv(A_np)

array([[-1.53333333,  1.46666667, -0.13333333],
       [ 0.33333333, -0.66666667,  0.33333333],
       [ 0.2       ,  0.2       , -0.2       ]])

Проведем проверку

In [25]:
LA.multiply(A, LA.inverse(A))

[[1.0, 2.220446049250313e-16, -2.220446049250313e-16],
 [-2.220446049250313e-16, 1.0000000000000002, -2.220446049250313e-16],
 [-4.440892098500626e-16, -4.440892098500626e-16, 1.0]]

In [26]:
np.dot(A_np, np.linalg.inv(A_np))

array([[ 1.00000000e+00,  1.11022302e-16, -1.11022302e-16],
       [ 3.88578059e-16,  1.00000000e+00,  5.55111512e-17],
       [ 4.44089210e-16,  0.00000000e+00,  1.00000000e+00]])

В обоих функциях присутствует погрешность при работе с типом float.

Проверим работу функции divide.

Cравним результат вычисления с помощью комбинации функций из numpy - dot, linalg.inv

In [27]:
LA.divide(A, B)

[[1.4320987654320985, -0.8888888888888888, 0.8765432098765432],
 [1.5432098765432098, -0.8888888888888888, 0.9876543209876543],
 [0.691358024691358, -1.2222222222222223, 1.8024691358024691]]

In [28]:
np.dot(A_np, np.linalg.inv(B_np))

array([[ 1.43209877, -0.88888889,  0.87654321],
       [ 1.54320988, -0.88888889,  0.98765432],
       [ 0.69135802, -1.22222222,  1.80246914]])

Результаты вычислений сходятся.

Проверим поэлементное деление матрицы на матрицу c помощью функции divide.

Сравним результат вычисления с аналогичной функцией из numpy - divide.

In [29]:
LA.divide(A, B, elements=True)

[[0.5, 4.0, 2.0],
 [0.2222222222222222, 1.0, 1.75],
 [0.42857142857142855, 1.125, 1.3333333333333333]]

In [30]:
np.divide(A_np, B_np)

array([[0.5       , 4.        , 2.        ],
       [0.22222222, 1.        , 1.75      ],
       [0.42857143, 1.125     , 1.33333333]])

Для векторов

In [31]:
def get_divide_vectors_print(vec1, vec2):    
    print("Векторы: ", 
          "вектор 1:", vec1, 
          sep="\n",)
    print("вектор 2:" if isinstance(vec2, list) else "скаляр")
    print(vec2, end="\n\n")
    print("linear_algebra:")
    print(*LA.divide(vec1, vec2, elements=True), sep="\n", end="\n\n")
    print("numpy:")
    print(np.divide(np.array(vec1), np.array(vec2)))

In [32]:
get_divide_vectors_print(X_1, X_2)
print("="*40, end="\n\n")
get_divide_vectors_print(Y_1, Y_2)

Векторы: 
вектор 1:
[[1, 2, 3]]
вектор 2:
[[4, 7, 8]]

linear_algebra:
[0.25, 0.2857142857142857, 0.375]

numpy:
[[0.25       0.28571429 0.375     ]]

Векторы: 
вектор 1:
[[3], [2], [4]]
вектор 2:
[[4], [7], [9]]

linear_algebra:
[0.75]
[0.2857142857142857]
[0.4444444444444444]

numpy:
[[0.75      ]
 [0.28571429]
 [0.44444444]]


Деление векторов на число

In [33]:
get_divide_vectors_print(X_1, 2)
print("="*40, end="\n\n")
get_divide_vectors_print(Y_1, 2)

Векторы: 
вектор 1:
[[1, 2, 3]]
скаляр
2

linear_algebra:
[0.5, 1.0, 1.5]

numpy:
[[0.5 1.  1.5]]

Векторы: 
вектор 1:
[[3], [2], [4]]
скаляр
2

linear_algebra:
[1.5]
[1.0]
[2.0]

numpy:
[[1.5]
 [1. ]
 [2. ]]


Результаты вычислений сходятся.

Проверим вычисление для матриц разной размерности.

In [34]:
LA.divide(A, Z)

Невозможно поделить объекты. Разная размерность.


In [35]:
LA.divide(A, A_4x5)

Вторая матрица не является квадратной.
Обратную матрицу можно найти только для квадратной матрицы
Деление матриц произвести невозможно.


Случай с вырожденной матрицей.

In [36]:
LA.divide(A, C)

Определитель второй матрицы равен 0.
Матрица является вырожденной.
Обратную матрицу можно найти только для невырожденной квадратной матрицы.
Деление матриц произвести невозможно.


Также проверим деление матриц и векторов на число.

In [37]:
for i in range(0, len(list_np_arrays), 2):
    get_result_print(names[i], 
                     list_py_arrays[i],
                     list_np_arrays[i],
                     function=LA.divide,
                     function_np=np.divide,
                     scaler=2)

Матрицы

Исходные объекты:
[[1 4 6]
 [2 5 7]
 [3 9 8]]
2

----------------------------------------
Результат работы функции деления

linearalgebra:
[0.5, 2.0, 3.0]
[1.0, 2.5, 3.5]
[1.5, 4.5, 4.0]

numpy:
[[0.5 2.  3. ]
 [1.  2.5 3.5]
 [1.5 4.5 4. ]]

Вектор-строка

Исходные объекты:
[[1 2 3]]
2

----------------------------------------
Результат работы функции деления

linearalgebra:
[0.5, 1.0, 1.5]

numpy:
[[0.5 1.  1.5]]

Вектор-столбец

Исходные объекты:
[[3]
 [2]
 [4]]
2

----------------------------------------
Результат работы функции деления

linearalgebra:
[1.5]
[1.0]
[2.0]

numpy:
[[1.5]
 [1. ]
 [2. ]]



Вывод: функция divide работает корректно.

## 05. Транспонирование
<a id='transpose'></a>

Транспонированная матрица — матрица $A^{T}$, полученная из исходной матрицы $A$ заменой строк на столбцы.

Функция транспонирование для матриц и векторов - transpose.

Сравним результат вычисления с аналогичной функцией из numpy - transpose.

In [38]:
def get_one_arg_func_result(name, 
                            py_obj, 
                            np_obj, 
                            function=None, 
                            function_np=None):
    print(f"{name}:", end="\n\n")
    print("Исходный объект:")
    print(*py_obj, sep="\n")
    print("-"*26, end="\n\n")
    print("Результаты работы функций:", end="\n\n")
    print("linearalgebra:")
    if isinstance(function(py_obj), list):
        print(*function(py_obj),
              sep="\n", end="\n\n")
    else:
        print(function(py_obj), end="\n\n")
    print("numpy:")
    print(function_np(np_obj))
    print("="*26, end="\n\n")

In [39]:
for i in range(0, len(list_np_arrays), 2):
    get_one_arg_func_result(names[i],
                            list_py_arrays[i],
                            list_np_arrays[i],
                            function=LA.transpose,
                            function_np=np.transpose)

Матрицы:

Исходный объект:
[1, 4, 6]
[2, 5, 7]
[3, 9, 8]
--------------------------

Результаты работы функций:

linearalgebra:
[1, 2, 3]
[4, 5, 9]
[6, 7, 8]

numpy:
[[1 2 3]
 [4 5 9]
 [6 7 8]]

Вектор-строка:

Исходный объект:
[1, 2, 3]
--------------------------

Результаты работы функций:

linearalgebra:
[1]
[2]
[3]

numpy:
[[1]
 [2]
 [3]]

Вектор-столбец:

Исходный объект:
[3]
[2]
[4]
--------------------------

Результаты работы функций:

linearalgebra:
[3, 2, 4]

numpy:
[[3 2 4]]



Случай неквадратных матриц.

In [40]:
get_one_arg_func_result("Матрица размером 4x5",
                        A_4x5,
                        A_4x5_np,
                        function=LA.transpose,
                        function_np=np.transpose)

Матрица размером 4x5:

Исходный объект:
[1, 2, 3, 4, 5]
[3, 5, 7, 9, 1]
[4, 6, 6, 7, 4]
[7, 5, 5, 8, 9]
--------------------------

Результаты работы функций:

linearalgebra:
[1, 3, 4, 7]
[2, 5, 6, 5]
[3, 7, 6, 5]
[4, 9, 7, 8]
[5, 1, 4, 9]

numpy:
[[1 3 4 7]
 [2 5 6 5]
 [3 7 6 5]
 [4 9 7 8]
 [5 1 4 9]]



Вывод: функция transpose работает корректно.

## 06. Определитель
<a id='determinant'></a>

Проверим функцию нахождения определителя матриц, реализованную в модуле linearalgebra - get_deteminant.

Сравним результат вычисления с аналогичной функцией из numpy - linalg.det.

In [41]:
get_one_arg_func_result("Определитель матрицы",
                        A,
                        A_np,
                        function=LA.get_determinant,
                        function_np=np.linalg.det)

Определитель матрицы:

Исходный объект:
[1, 4, 6]
[2, 5, 7]
[3, 9, 8]
--------------------------

Результаты работы функций:

linearalgebra:
15

numpy:
15.0



In [42]:
get_one_arg_func_result("Определитель матрицы размера 2x2",
                        Z,
                        Z_np,
                        function=LA.get_determinant,
                        function_np=np.linalg.det)

Определитель матрицы размера 2x2:

Исходный объект:
[1, 2]
[3, 5]
--------------------------

Результаты работы функций:

linearalgebra:
-1

numpy:
-1.0000000000000004



Для квадратной матрицы большей размерности.

In [43]:
A_6x6 = [[1, 2, 3, 4, 5, 6],
         [3, 5, 7, 9, 1, 9],
         [4, 6, 6, 7, 4, 0],
         [7, 5, 5, 8, 9, 1],
         [2, 5, 6, 0, 1, 2],
         [1, 4, 9, 7, 2, 8]]
A_6x6_np = np.array(A_6x6)

get_one_arg_func_result("Определитель матрицы размера 6x6",
                        A_6x6,
                        A_6x6_np,
                        function=LA.get_determinant,
                        function_np=np.linalg.det)

Определитель матрицы размера 6x6:

Исходный объект:
[1, 2, 3, 4, 5, 6]
[3, 5, 7, 9, 1, 9]
[4, 6, 6, 7, 4, 0]
[7, 5, 5, 8, 9, 1]
[2, 5, 6, 0, 1, 2]
[1, 4, 9, 7, 2, 8]
--------------------------

Результаты работы функций:

linearalgebra:
-21712

numpy:
-21711.999999999993



Для случая неквадратной матрицы большей размерности.

In [44]:
print("Определитель матрицы размера 4x5",
      *A_4x5, sep="\n")
LA.get_determinant(A_4x5)

Определитель матрицы размера 4x5
[1, 2, 3, 4, 5]
[3, 5, 7, 9, 1]
[4, 6, 6, 7, 4]
[7, 5, 5, 8, 9]
Для неквадратной матрицы невозможно найти определитель


Определитель для случая вырожденной матрицы.

In [45]:
get_one_arg_func_result("Определитель матрицы",
                        C,
                        C_np,
                        function=LA.get_determinant,
                        function_np=np.linalg.det)

Определитель матрицы:

Исходный объект:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
--------------------------

Результаты работы функций:

linearalgebra:
0

numpy:
0.0



In [46]:
LA.is_singular(C)

True

Вывод: функция transpose для нахождения определителя работает корректно.

## Общий вывод
<a id='recap'></a>

Согласно тестовому заданию разработан модуль linearalgebra для работы с базовой линейной алгеброй, при помощи стандартной библиотеки Python.

Библиотека numpy использовалась только в рамках отчета о работе функций, для наглядного сравнения результатов вычислений.

Все функции реализованные в модуле linearalgebra работают корректно.